/* Nexathon II paper-presentation deck — generated from repo artifacts.
 * Numbers: ds/models/paper/paper_numbers.json (same source as the paper macros).
 * References: paper/main.md "## References" (same set as the PDF, [1]-[13]).
 * Figures: ds/models/paper/*.png (generated by ds/paper_figures.py).
 * Run: node ppt/make_deck.js  ->  ppt/paper_presentation.pptx
 */
const pptxgen = require('pptxgenjs');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(__dirname, 'paper_presentation.pptx');

/* ---------- data (fail loud on missing keys) ---------- */
const RAW = JSON.parse(fs.readFileSync(path.join(ROOT, 'ds', 'models', 'paper', 'paper_numbers.json'), 'utf8'));
const flat = (o, p = '') => Object.entries(o).reduce((acc, [k, val]) => {
  const kk = p ? p + '.' + k : k;
  if (val && typeof val === 'object' && !Array.isArray(val)) Object.assign(acc, flat(val, kk));
  else acc[kk] = val;
  return acc;
}, {});
const F = flat(RAW);
const v = (k) => { if (!(k in F)) throw new Error('missing number key: ' + k); return F[k]; };
const fx = (k, d = 3) => Number(v(k)).toFixed(d);
const pc = (k, d = 1) => (v(k) * 100).toFixed(d) + '%';
const nfmt = (k) => Number(v(k)).toLocaleString('en-US');

const md = fs.readFileSync(path.join(ROOT, 'paper', 'main.md'), 'utf8');
const refs = md.split('## References')[1].split('\n').map((l) => l.trim()).filter((l) => /^\[\d+\]/.test(l));
if (refs.length !== 13) throw new Error('expected 13 references, got ' + refs.length);

const FIG = (n) => path.join(ROOT, 'ds', 'models', 'paper', n);

/* ---------- design tokens ---------- */
const DARK = '0A3D46', DARK2 = '0E5560', PRIMARY = '028090', SEAFOAM = '00A896', MINT = '02C39A';
const INK = '12343B', INK2 = '35565D', MUTED = '5F7E85', CARD = 'EFF7F7', LINE = 'DCEBEB';
const AMBER = '8F5200', AMBERBG = 'FBF0DE', WHITE = 'FFFFFF', ICE = 'A8CDD0';
const HEAD = 'Cambria', BODY = 'Calibri';
const ST = pptxgen.ShapeType || { roundRect: 'roundRect', ellipse: 'ellipse', rect: 'rect' };

const shadow = () => ({ type: 'outer', color: '7FA8AC', blur: 7, offset: 2, angle: 90, opacity: 0.28 });

const pres = new pptxgen();
pres.layout = 'LAYOUT_WIDE'; /* 13.33 x 7.5 */
pres.author = 'Placeholder Department';
pres.subject = 'Nexathon II paper presentation';
pres.title = 'Real-Data Machine Learning for Telemedicine Triage and Outbreak Surveillance';

const card = (s, x, y, w, h, fill = CARD) =>
  s.addShape(ST.roundRect, { x, y, w, h, fill: { color: fill }, line: { color: LINE, width: 0.75 }, rectRadius: 0.08, shadow: shadow() });

const glyph = (s, x, y, txt, { size = 0.46, fill = MINT, color = DARK, fs = 15, shape = ST.ellipse } = {}) =>
  s.addText(txt, { shape, x, y, w: size, h: size, fill: { color: fill }, align: 'center', valign: 'middle', margin: 0, fontFace: BODY, fontSize: fs, bold: true, color });

const title = (s, txt, dark = false) =>
  s.addText(txt, { x: 0.6, y: 0.38, w: 12.1, h: 0.75, fontFace: HEAD, fontSize: 29, bold: true, color: dark ? WHITE : INK, margin: 0 });

const slideNum = (s, n, dark = false) =>
  s.addText(String(n).padStart(2, '0'), { x: 12.55, y: 7.08, w: 0.45, h: 0.28, fontFace: BODY, fontSize: 9.5, color: dark ? ICE : MUTED, align: 'right', margin: 0 });

const chip = (s, x, y, w, h, txt, { fill = WHITE, linec = LINE, txtc = INK2, gtxt = '\u2713', gfill = MINT, gcolor = DARK, fs = 12.5, bold = false } = {}) => {
  s.addShape(ST.roundRect, { x, y, w, h, fill: { color: fill }, line: { color: linec, width: 0.75 }, rectRadius: 0.07, shadow: shadow() });
  glyph(s, x + 0.14, y + (h - 0.36) / 2, gtxt, { size: 0.36, fill: gfill, color: gcolor, fs: 12 });
  s.addText(txt, { x: x + 0.6, y, w: w - 0.74, h, fontFace: BODY, fontSize: fs, bold, color: txtc, valign: 'middle', margin: 0 });
};

const stat = (s, x, y, w, h, o) => {
  card(s, x, y, w, h);
  const big = h >= 2.4;
  const vfs = o.fs || (big ? 33 : 25);
  s.addText(o.value, { x: x + 0.2, y: y + (big ? 0.16 : 0.1), w: w - 0.4, h: big ? 0.72 : 0.52, fontFace: HEAD, fontSize: vfs, bold: true, color: o.valColor || PRIMARY, margin: 0 });
  s.addText(o.label, { x: x + 0.2, y: y + (big ? 0.95 : 0.64), w: w - 0.4, h: big ? 0.4 : 0.34, fontFace: BODY, fontSize: big ? 14.5 : 13, bold: true, color: INK, margin: 0 });
  s.addText(o.sub, { x: x + 0.2, y: y + (big ? 1.38 : 1.0), w: w - 0.4, h: h - (big ? 1.52 : 1.1), fontFace: BODY, fontSize: big ? 11.5 : 10.5, color: INK2, margin: 0 });
};

const img = (s, file, x, y, w, h) => s.addImage({ path: FIG(file), x, y, w, h, sizing: { type: 'contain', w, h } });

const row = (s, y, g, head, body, { gc = MINT, gtxt } = {}) => {
  glyph(s, 0.6, y + 0.04, gtxt || g, { size: 0.5, fill: gc, color: gc === AMBERBG ? AMBER : DARK, fs: gc === AMBERBG ? 16 : 14 });
  s.addText([
    { text: head + ' \u2014 ', options: { bold: true, color: INK } },
    { text: body, options: { color: INK2 } },
  ], { x: 1.32, y, w: 11.4, h: 1.05, fontFace: BODY, fontSize: 14, margin: 0, valign: 'top' });
};

/* ================================================================ S1 title */
{
  const s = pres.addSlide();
  s.background = { color: DARK };
  s.addShape(ST.ellipse, { x: 9.4, y: -2.2, w: 7.2, h: 7.2, fill: { color: SEAFOAM, transparency: 86 }, line: { type: 'none' } });
  s.addShape(ST.ellipse, { x: 11.4, y: 4.9, w: 3.6, h: 3.6, fill: { color: MINT, transparency: 80 }, line: { type: 'none' } });
  s.addText('Real-Data Machine Learning for Telemedicine Triage and Outbreak Surveillance',
    { x: 0.9, y: 1.75, w: 11.2, h: 1.95, fontFace: HEAD, fontSize: 36, bold: true, color: WHITE, margin: 0 });
  s.addText('Author One, Author Two  \u00B7  Placeholder Department, Placeholder Institute, City, India',
    { x: 0.9, y: 3.9, w: 11.2, h: 0.4, fontFace: BODY, fontSize: 15.5, color: ICE, margin: 0 });
  s.addText('Nexathon II  \u00B7  Paper Presentation  \u00B7  AIKTC  \u00B7  9 October 2026',
    { x: 0.9, y: 4.42, w: 11.2, h: 0.4, fontFace: BODY, fontSize: 15, bold: true, color: MINT, margin: 0 });
  s.addText('Public real-world data only  \u00B7  no synthetic records  \u00B7  released for exact reproduction',
    { x: 0.9, y: 4.94, w: 11.2, h: 0.4, fontFace: BODY, fontSize: 13.5, italic: true, color: ICE, margin: 0 });
  const cw = 3.62, gap = 0.2, x0 = 0.9;
  chip(s, x0, 6.1, cw, 0.6, 'IEEE 6-page paper, 13 references', { fill: DARK2, linec: DARK2, txtc: WHITE, gfill: MINT, fs: 12 });
  chip(s, x0 + cw + gap, 6.1, cw, 0.6, 'Seed-42 byte-identical reruns', { fill: DARK2, linec: DARK2, txtc: WHITE, gfill: MINT, gtxt: '#', fs: 12 });
  chip(s, x0 + 2 * (cw + gap), 6.1, cw, 0.6, 'Fail-closed data pipeline', { fill: DARK2, linec: DARK2, txtc: WHITE, gfill: MINT, gtxt: '!', fs: 12 });
  s.addNotes('Opening: two everyday decisions on a rural telemedicine platform, answered only with public data. Byline is a placeholder in the current draft.');
}

/* ================================================================ S2 problem */
{
  const s = pres.addSlide();
  title(s, 'Two decisions, asymmetric errors');
  const y = 1.4, h = 4.35, w = 5.9;
  card(s, 0.6, y, w, h); card(s, 6.83, y, w, h);
  glyph(s, 0.9, y + 0.3, '1', { size: 0.5, fill: PRIMARY, color: WHITE, fs: 16 });
  s.addText('Patient-level triage', { x: 1.56, y: y + 0.3, w: w - 1.26, h: 0.5, fontFace: HEAD, fontSize: 19, bold: true, color: INK, valign: 'middle', margin: 0 });
  s.addText('Which callers can be managed remotely, and which need urgent escalation? Errors are asymmetric: a missed high-acuity patient is a safety event, while an unnecessary referral costs access and trust.',
    { x: 0.9, y: y + 0.92, w: w - 0.6, h: 2.0, fontFace: BODY, fontSize: 14, color: INK2, margin: 0 });
  s.addText('Constraint: ' + pc('module1_triage.prevalence') + ' of encounters are high-acuity; uncertain cases must be deferred, not guessed.',
    { x: 0.9, y: y + 3.25, w: w - 0.6, h: 0.85, fontFace: BODY, fontSize: 12, italic: true, color: MUTED, margin: 0 });

  glyph(s, 7.13, y + 0.3, '2', { size: 0.5, fill: SEAFOAM, color: WHITE, fs: 16 });
  s.addText('Population-level outbreak signal', { x: 7.79, y: y + 0.3, w: w - 1.26, h: 0.5, fontFace: HEAD, fontSize: 19, bold: true, color: INK, valign: 'middle', margin: 0 });
  s.addText('Is this district-week part of a developing wave? In routine public surveillance there is no outbreak label to train on \u2014 only a fixed weekly review budget, so every alert displaces another.',
    { x: 7.13, y: y + 0.92, w: w - 0.6, h: 2.0, fontFace: BODY, fontSize: 14, color: INK2, margin: 0 });
  s.addText('Constraint: a top-5% alert budget, and evaluation that must stay descriptive.',
    { x: 7.13, y: y + 3.25, w: w - 0.6, h: 0.85, fontFace: BODY, fontSize: 12, italic: true, color: MUTED, margin: 0 });

  chip(s, 0.6, 6.2, 12.13, 0.66, 'Both layers run on ordinary public data \u2014 no proprietary EHR, no private sensor feed, no synthetic records.',
    { fill: WHITE, gfill: MINT, fs: 13, bold: true });
  slideNum(s, 2);
  s.addNotes('Frame the two decisions and their asymmetric error costs. Surveillance has no labels, which dictates an alert-budget, descriptive evaluation.');
}

/* ================================================================ S3 data */
{
  const s = pres.addSlide();
  title(s, 'Three real public datasets \u2014 nothing synthetic');
  const y = 1.45, h = 2.95, w = 3.95, gap = 0.14, x0 = 0.6;
  stat(s, x0, y, w, h, { value: nfmt('module1_triage.n_analysis'), label: 'ED analysis encounters', sub: 'CDC NHAMCS 2019 public microdata (' + nfmt('module1_triage.n_raw') + ' raw, protocol exclusions applied)  [1]' });
  stat(s, x0 + w + gap, y, w, h, { value: nfmt('module2_outbreak.district_weeks'), label: 'district-weeks of SARI signals', sub: 'covid19india public archive, ' + nfmt('module2_outbreak.districts') + ' districts, 2020\u20132023  [2]', valColor: SEAFOAM });
  stat(s, x0 + 2 * (w + gap), y, w, h, { value: nfmt('supplement_forecast.months_analyzed'), label: 'months of pharmacy sales', sub: 'Kaggle monthly series, CC BY-NC 4.0 \u2014 supplementary forecast task  [3]', valColor: PRIMARY });
  const cy = 4.72, cw = 3.95;
  chip(s, x0, cy, cw, 0.62, 'Missing raw file \u21D2 hard FileNotFoundError', { fill: WHITE, gfill: AMBERBG, gtxt: '!', gcolor: AMBER, fs: 11.5 });
  chip(s, x0 + cw + gap, cy, cw, 0.62, 'Seed 42 \u2014 byte-identical reruns', { fill: WHITE, gfill: MINT, gtxt: '#', fs: 11.5 });
  chip(s, x0 + 2 * (cw + gap), cy, cw, 0.62, '0 synthetic rows anywhere in the pipeline', { fill: WHITE, gfill: MINT, fs: 11.5 });
  s.addText('Every dataset is public and licensed; URLs, retrieval dates and licences are cited in the paper \u2014 see Data Availability.',
    { x: 0.6, y: 5.72, w: 12.1, h: 0.4, fontFace: BODY, fontSize: 12.5, italic: true, color: MUTED, margin: 0 });
  slideNum(s, 3);
  s.addNotes('All three sources are free and public. NHAMCS and covid19india carry DOI/URL citations; Kaggle is CC BY-NC. Fail-closed means a stale download cannot silently degrade results.');
}

/* ================================================================ S4 methods */
{
  const s = pres.addSlide();
  title(s, 'Two modules, one reproducible pipeline');
  s.addShape(ST.roundRect, { x: 0.6, y: 1.35, w: 6.7, h: 4.4, fill: { color: WHITE }, line: { color: LINE, width: 0.75 }, rectRadius: 0.08, shadow: shadow() });
  img(s, 'paper_fig0_pipeline.png', 0.75, 1.5, 6.4, 4.1);
  const x = 7.55, w = 5.18;
  card(s, x, 1.35, w, 2.1);
  glyph(s, x + 0.22, 1.58, '1', { size: 0.44, fill: PRIMARY, color: WHITE, fs: 14 });
  s.addText('Module 1 \u2014 patient triage', { x: x + 0.78, y: 1.58, w: w - 1.0, h: 0.44, fontFace: BODY, fontSize: 15.5, bold: true, color: INK, valign: 'middle', margin: 0 });
  s.addText('Calibrated XGBoost (isotonic) risk score \u2192 cross-fitted tuned threshold \u2192 abstention for uncertain cases \u2192 PAC split-conformal recall control at \u03B1 = ' + fx('module1_triage.conformal_alpha', 2) + '.',
    { x: x + 0.22, y: 2.12, w: w - 0.44, h: 1.2, fontFace: BODY, fontSize: 12.5, color: INK2, margin: 0 });
  card(s, x, 3.65, w, 2.1);
  glyph(s, x + 0.22, 3.88, '2', { size: 0.44, fill: SEAFOAM, color: WHITE, fs: 14 });
  s.addText('Module 2 \u2014 district outbreak signal', { x: x + 0.78, y: 3.88, w: w - 1.0, h: 0.44, fontFace: BODY, fontSize: 15.5, bold: true, color: INK, valign: 'middle', margin: 0 });
  s.addText('IsolationForest anomaly score per district-week \u2192 fixed 5% weekly alert budget \u2192 top-scoring district-weeks surfaced for review, then described retrospectively.',
    { x: x + 0.22, y: 4.42, w: w - 0.44, h: 1.2, fontFace: BODY, fontSize: 12.5, color: INK2, margin: 0 });
  chip(s, 0.6, 6.1, 12.13, 0.66, 'Both modules recompute from raw CSVs; every table and figure in the paper is a generated artifact \u2014 never hand-edited.',
    { fill: WHITE, gfill: MINT, fs: 13 });
  slideNum(s, 4);
  s.addNotes('Pipeline figure straight from the paper. Emphasise: thresholds are tuned on validation folds only; the conformal layer wraps the tuned model.');
}

/* ================================================================ S5 triage results */
{
  const s = pres.addSlide();
  title(s, 'Module 1 \u2014 discrimination and operating point');
  s.addShape(ST.roundRect, { x: 0.6, y: 1.35, w: 6.55, h: 5.3, fill: { color: WHITE }, line: { color: LINE, width: 0.75 }, rectRadius: 0.08, shadow: shadow() });
  img(s, 'paper_fig1_roc.png', 0.75, 1.5, 6.25, 4.75);
  s.addText('Cross-validated ROC, seed 42 \u2014 regenerated from ds/paper_figures.py.',
    { x: 0.75, y: 6.28, w: 6.25, h: 0.3, fontFace: BODY, fontSize: 10.5, italic: true, color: MUTED, margin: 0 });
  const x1 = 7.4, x2 = 10.3, w = 2.75, h = 2.5, y1 = 1.35, y2 = 4.05;
  const aucCI = v('module1_triage.auc_xgb_ci95');
  stat(s, x1, y1, w, h, { value: fx('module1_triage.auc_xgb_cv'), label: 'primary model CV AUC', sub: 'vs ' + fx('module1_triage.auc_logreg_cv') + ' logistic; 95% CI [' + aucCI[0] + ', ' + aucCI[1] + ']' });
  stat(s, x2, y1, w, h, { value: pc('module1_triage.nested_under_triage'), label: 'under-triage, cross-fitted', sub: 'down from ' + pc('module1_triage.xgb_cv_t05_under_triage') + ' at default t = 0.50; FPR ' + fx('module1_triage.nested_fpr') });
  stat(s, x1, y2, w, h, { value: fx('module1_triage.nested_recall'), label: 'recall at the chosen point', sub: 'precision ' + fx('module1_triage.nested_precision') + '; thresholds ' + fx('module1_triage.nested_threshold_min', 2) + '\u2013' + fx('module1_triage.nested_threshold_max', 2) + ' per outer fold', valColor: SEAFOAM });
  stat(s, x2, y2, w, h, { value: fx('module1_triage.brier_primary_oof'), label: 'OOF Brier, isotonic', sub: 'beats ' + fx('module1_triage.brier_constant_oof') + ' for a constant \u2014 calibration holds', valColor: SEAFOAM });
  slideNum(s, 5);
  s.addNotes('Under-triage is the metric the platform cares about: the default t=0.5 threshold with a calibrated model is far too conservative (85.9% under-triage), so cross-fitted threshold selection is the lever. The nested estimate tunes each outer fold on the other four only \u2014 no test-fold peeking. Brier below the constant baseline means the probabilities are calibrated enough to threshold.');
}

/* ================================================================ S6 conformal */
{
  const s = pres.addSlide();
  title(s, 'Split-conformal recall control \u2014 marginal vs PAC');
  s.addShape(ST.roundRect, { x: 0.6, y: 1.3, w: 6.0, h: 4.0, fill: { color: WHITE }, line: { color: LINE, width: 0.75 }, rectRadius: 0.08, shadow: shadow() });
  img(s, 'paper_fig4_conformal_hist.png', 0.72, 1.42, 5.76, 3.76);
  s.addText('Recall distribution over ' + nfmt('module1_triage.conformal_n_seeds') + ' random splits, both rules, \u03B1 = ' + fx('module1_triage.conformal_alpha', 2) + '.',
    { x: 0.6, y: 5.36, w: 6.0, h: 0.3, fontFace: BODY, fontSize: 10.5, italic: true, color: MUTED, margin: 0 });
  s.addShape(ST.roundRect, { x: 6.9, y: 1.3, w: 5.83, h: 4.0, fill: { color: WHITE }, line: { color: LINE, width: 0.75 }, rectRadius: 0.08, shadow: shadow() });
  img(s, 'paper_fig3_tradeoff.png', 7.02, 1.42, 5.59, 3.76);
  s.addText('Threshold\u2013coverage trade-off, split means \u00B1 SD.',
    { x: 6.9, y: 5.36, w: 5.83, h: 0.3, fontFace: BODY, fontSize: 10.5, italic: true, color: MUTED, margin: 0 });
  chip(s, 0.6, 5.9, 6.0, 0.95,
    'Marginal rule: mean recall ' + fx('module1_triage.conformal_mean_recall') + ' (SD ' + fx('module1_triage.conformal_sd_recall') + '), yet ' + pc('module1_triage.conformal_frac_below_085', 1) +
    ' of splits fall below the 0.85 target \u2014 average-case only.',
    { fill: AMBERBG, linec: 'E8D5AC', txtc: AMBER, gfill: AMBER, gtxt: '!', gcolor: WHITE, fs: 12.5, bold: true });
  chip(s, 6.73, 5.9, 6.0, 0.95,
    'PAC rule (\u03B4 = ' + pc('module1_triage.pac_delta', 0) + '): mean recall ' + fx('module1_triage.pac_mean_recall') +
    ', below-target splits cut to ' + pc('module1_triage.pac_frac_below_085', 1) + ' at precision ' + fx('module1_triage.pac_mean_precision') + '.',
    { fill: WHITE, gfill: MINT, fs: 12.5, bold: true });
  slideNum(s, 6);
  s.addNotes('The honest core: the textbook conformal rule is marginal \u2014 12.5% of the 200 splits miss the nominal 0.85 target. The PAC (Beta order-statistic) rule buys a per-split-style bound: below-target share drops to 3.5% (within delta=10%) with slightly higher mean recall; the price is a lower threshold and precision 0.191 vs 0.196. Both rules are stated in the abstract, results and conclusion.');
}

/* ================================================================ S7 outbreak */
{
  const s = pres.addSlide();
  title(s, 'Module 2 \u2014 outbreak surveillance, described not claimed');
  s.addShape(ST.roundRect, { x: 0.6, y: 1.35, w: 6.9, h: 3.3, fill: { color: WHITE }, line: { color: LINE, width: 0.75 }, rectRadius: 0.08, shadow: shadow() });
  img(s, 'paper_fig5_outbreak.png', 0.72, 1.47, 6.66, 3.06);
  s.addText('Weekly IsolationForest flags across ' + nfmt('module2_outbreak.district_weeks') + ' district-weeks \u2014 regenerated from ds/paper_figures.py.',
    { x: 0.6, y: 4.72, w: 6.9, h: 0.3, fontFace: BODY, fontSize: 10.5, italic: true, color: MUTED, margin: 0 });
  chip(s, 0.6, 5.35, 6.9, 1.4,
    'Descriptive only: no labelled outbreak ground truth exists in routine district data [2]. Enrichment is retrospective description at a fixed budget \u2014 not a validated detector.',
    { fill: AMBERBG, linec: 'E8D5AC', txtc: AMBER, gfill: AMBER, gtxt: '!', gcolor: WHITE, fs: 12.5 });
  const x = 7.75, w = 4.98, h = 1.42, g = 0.24;
  stat(s, x, 1.35, w, h, { value: Number(v('module2_outbreak.delta_enrichment')).toFixed(1) + '\u00D7', label: 'Delta-wave enrichment', sub: 'flag rate inside the wave vs background', valColor: PRIMARY, fs: 24 });
  stat(s, x, 1.35 + h + g, w, h, { value: Number(v('module2_outbreak.iso_single_delta_lead_weeks')) + ' weeks', label: 'median lead over the wave', sub: 'at the fixed 5% alert budget', valColor: SEAFOAM, fs: 24 });
  stat(s, x, 1.35 + 2 * (h + g), w, h, { value: pc('module2_outbreak.iso_single_delta_flag_rate', 0), label: 'of Delta weeks flagged', sub: 'vs ' + pc('module2_outbreak.delta_outside_flag_rate') + ' of weeks outside it', valColor: SEAFOAM, fs: 24 });
  slideNum(s, 7);
  s.addNotes('Biggest enrichment is on the Delta wave with a two-week median lead. Caveat is printed on the slide: no outbreak labels, so this is description at a fixed budget.');
}

/* ================================================================ S8 honesty */
{
  const s = pres.addSlide();
  title(s, 'What we do not claim');
  row(s, 1.3, '!', 'Guarantees rest on exchangeability', 'The marginal rule is average-case (' + pc('module1_triage.conformal_frac_below_085', 1) + ' of splits below target); PAC bounds that share at \u03B4 = ' + pc('module1_triage.pac_delta', 0) + ', but neither survives distribution shift.', { gc: AMBERBG, gtxt: '!' });
  row(s, 2.45, '2', 'Transfer is unproven', 'Trained on US NHAMCS emergency-department data; rural Indian telemedicine casemix and workflow differ. External validation is future work, not a result.', { gc: AMBERBG, gtxt: '2' });
  row(s, 3.6, '3', 'Calibrated, not oracular', 'Isotonic Brier ' + fx('module1_triage.brier_primary_oof') + ' beats the constant ' + fx('module1_triage.brier_constant_oof') + ' \u2014 but probabilities are not validated absolute risks; they drive thresholds, not quotations.', { gc: AMBERBG, gtxt: '3' });
  row(s, 4.75, '4', 'Outbreak detection is descriptive', 'IsolationForest enrichment is retrospective description at a 5% budget; naive baselines and NEWS2 stay competitive (cutoff 1: precision ' + fx('module1_triage.news2_cutoff1_precision') + ', recall ' + fx('module1_triage.news2_cutoff1_recall') + ').', { gc: AMBERBG, gtxt: '4' });
  chip(s, 0.6, 6.15, 12.13, 0.66, 'All ten mandated disclosures are machine-checked in paper/audit.py and pass \u2014 full text in Section V of the paper.',
    { fill: WHITE, gfill: MINT, fs: 13 });
  slideNum(s, 8);
  s.addNotes('Read these aloud if time is short. Judges reward calibrated claims: each limitation here is also stated in the abstract or results of the paper.');
}

/* ================================================================ S9 reproducibility */
{
  const s = pres.addSlide();
  title(s, 'Reproducible by construction');
  const w = 5.93, h = 1.98, x1 = 0.6, x2 = 6.8, y1 = 1.4, y2 = 3.62;
  const boxes = [
    [x1, y1, '\u2713', MINT, 'Fail-closed data pipeline', 'A missing or stale raw file raises FileNotFoundError. No silent imputation, no synthetic backfill, no cached numbers on disk.'],
    [x2, y1, '42', PRIMARY, 'Seed 42, byte-identical', 'Repeated runs produce identical CSVs and PNGs; published metrics are read back from generated artifacts at build time.'],
    [x1, y2, '#', SEAFOAM, 'One JSON behind every number', 'LaTeX, Markdown, DOCX and this deck all resolve metrics from paper_numbers.json \u2014 zero hand-typed figures.'],
    [x2, y2, '\u2605', MINT, 'Automated audits on every build', 'Numbers, citations, originality, honesty disclosures and IEEE format are machine-checked \u2014 all pass.'],
  ];
  for (const [x, y, g, gc, head, body] of boxes) {
    card(s, x, y, w, h);
    glyph(s, x + 0.24, y + 0.24, g, { size: 0.46, fill: gc, color: WHITE, fs: g.length > 1 ? 12 : 14 });
    s.addText(head, { x: x + 0.86, y: y + 0.24, w: w - 1.1, h: 0.46, fontFace: BODY, fontSize: 15.5, bold: true, color: INK, valign: 'middle', margin: 0 });
    s.addText(body, { x: x + 0.24, y: y + 0.85, w: w - 0.48, h: 1.0, fontFace: BODY, fontSize: 12.5, color: INK2, margin: 0 });
  }
  chip(s, 0.6, 6.2, 12.13, 0.66, 'github.com/vaibhav7087/curago_paper_version  \u00B7  MIT licence  \u00B7  data licences, URLs and retrieval dates in Data Availability',
    { fill: WHITE, gfill: MINT, gtxt: '\u2197', fs: 12.5, bold: true });
  slideNum(s, 9);
  s.addNotes('Reproducibility is treated as a feature of the pipeline, not a README promise: fail-closed inputs, deterministic seeds, and one numeric source of truth across four output formats.');
}

/* ================================================================ S10 takeaways */
{
  const s = pres.addSlide();
  s.background = { color: DARK };
  s.addShape(ST.ellipse, { x: -1.8, y: 5.4, w: 5.2, h: 5.2, fill: { color: SEAFOAM, transparency: 88 }, line: { type: 'none' } });
  title(s, 'Takeaways', true);
  const items = [
    ['1', 'Ordinary public data, tuned without test-fold peeking, beats naive baselines on both tasks \u2014 AUC ' + fx('module1_triage.auc_xgb_cv') + ' for triage (cross-fitted under-triage ' + pc('module1_triage.nested_under_triage') + ') and ' + Number(v('module2_outbreak.delta_enrichment')).toFixed(1) + '\u00D7 outbreak enrichment \u2014 with protocol limits stated up front.'],
    ['2', 'Guarantees must be priced: the marginal conformal rule leaves ' + pc('module1_triage.conformal_frac_below_085', 1) + ' of splits below target, and the PAC rule cuts that to ' + pc('module1_triage.pac_frac_below_085', 1) + ' at \u03B4 = ' + pc('module1_triage.pac_delta', 0) + ' \u2014 publish the failures alongside the mean.'],
    ['3', 'Reproducibility is a feature, not a footnote: fail-closed inputs, byte-identical seed-42 reruns, and one JSON behind every number in four output formats.'],
  ];
  let y = 1.75;
  for (const [g, txt] of items) {
    glyph(s, 0.9, y + 0.05, g, { size: 0.5, fill: MINT, color: DARK, fs: 16 });
    s.addText(txt, { x: 1.65, y, w: 10.9, h: 1.25, fontFace: BODY, fontSize: 15.5, color: WHITE, margin: 0, valign: 'top' });
    y += 1.42;
  }
  s.addText('Next: prospective validation on rural-Indian telemedicine casemix, drift monitoring, threshold re-tuning \u2014 SHAP, calibration and forecast artifacts ship with the repository.',
    { x: 0.9, y: 6.2, w: 11.5, h: 0.5, fontFace: BODY, fontSize: 13, italic: true, color: ICE, margin: 0 });
  slideNum(s, 10, true);
  s.addNotes('Close on the three claims the evidence actually supports, then the honest future-work list. Invite questions on the conformal layer or the transfer caveat.');
}

/* ================================================================ S11 references */
{
  const s = pres.addSlide();
  title(s, 'References');
  const opt = (r) => ({ text: r, options: { breakLine: true, paraSpaceAfter: 7, fontSize: 9.5, color: INK2 } });
  s.addText(refs.slice(0, 7).map(opt), { x: 0.6, y: 1.15, w: 6.1, h: 6.0, fontFace: BODY, margin: 0, valign: 'top' });
  s.addText(refs.slice(7).map(opt), { x: 6.85, y: 1.15, w: 6.1, h: 6.0, fontFace: BODY, margin: 0, valign: 'top' });
  slideNum(s, 11);
  s.addNotes('Same 13-item bibliography as the PDF, exported from the compiled .bbl \u2014 citation numbering is identical.');
}

pres.writeFile({ fileName: OUT }).then(() => {
  console.log('wrote', OUT, '| slides: 11 | refs:', refs.length, '| numbers: paper_numbers.json');
});
